name: Build and deploy Retro Gaming solution  

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - 'finished/**'
env:
  imageRepository: 'gamingwebapp'
  containerRegistry: 'local'
  deploymentFile: 'gamingwebapp.minikube.yaml'
  namespace: 'containerworkshop'
  DOCKER_REGISTRY: 'local/'

jobs:

  build:

    runs-on: ["self-hosted", "workshop"]

    steps:
    - uses: actions/checkout@v3

    - name: Build an image from Dockerfile
      working-directory: ./finished
      run: |
        docker compose build
        docker tag local/gamingwebapp:latest local/gamingwebapp:${{github.run_number}}
        docker tag local/leaderboardwebapi:latest local/leaderboardwebapi:${{github.run_number}}
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.0
      with:
        files: ${{github.workspace}}/finished/deployment/${{env.deploymentFile}}
      env: 
        Build.BuildId: ${{github.run_number}}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: deploymentfiles
        path: ${{github.workspace}}/finished/deployment/${{env.deploymentFile}}
  deploy:
    runs-on:  ["self-hosted", "workshop"]
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: deploymentfiles
    
    - name: Run kubectl on frontend.yaml file to deploy new version
      run: |
        cat ./${{env.deploymentFile}}
        kubectl apply -f ./${{env.deploymentFile}}